export const Update_Order_Front = 'Update_Order_Front';
export const Add_New_Orders = 'New_Replace_Orders';
export const Update_BookOrderForm_Values = 'Update_BookOrderForm_Values';
export const Order_Type_ask = 'ask';
export const Order_Type_bid = 'bid';
export const Total_Orders_TillNow = "Total_Order"
export const Clear_Prev_TotalOrders = "Clear_Prev_TotalOrders"
export const Clear_BookOrderForm_Values = "clear_BookOrderForm_Values"
export const Fetch_Stock_Symbols = "Fetch_Stock_Symbols";
export const Load_Stock_Symbols = "Load_Stock_Symbols";
export const Set_User_Details = "Set_User_Details";
export const Add_To_Ask_TOrders = "Add_To_Ask_TOrders";
export const Add_To_Bid_TOrders = "Add_To_Bid_TOrders";
export const Set_LoginForm_ValidityState = "Set_LoginForm_ValidityState";
export const Clear_BidAsk_List_Orders = "Clear_BidAsk_List_Orders"
export const Load_Booked_Orders = "Load_Booked_Orders";
export const Load_Executed_Orders = "Load_Executed_Orders";
export const Fetch_Booked_Orders = "Fetch_Booked_Orders";
export const Fetch_Executed_Orders = "Fetch_Executed_Orders";
export const Fetch_News_List = "Fetch_News_List";
export const Load_News_List = "Load_News_List";
export const Add_MinMax_Ask_TOrders = "Add_MinMax_Ask_TOrders";
export const Add_MinMax_Bid_TOrders = "Add_MinMax_Bid_TOrders";
export const Clear_MinMax_AskBid_TOrders = "Clear_MinMax_AskBid_TOrders";
export const Call_Login_Api = "Call_Login_Api";
export const Load_BidAsk_List = "Load_BidAsk_List";
export const OnRecieve_BidAsk_Data = "OnRecieve_BidAsk_Data";
export const Update_CreateGameForm_Values = "Update_CreateGameForm_Values";
export const Post_CreateGameForm_Values = "Post_CreateGameForm_Values";
export const Game_Created_Success = "Game_Created_Success";
export const Request_Posts = "Request_Posts";
export const Recieve_Posts = "Recieve_Posts";
export const RecieveError_Posts = "RecieveError_Posts";
export const Load_ALL_Games = "Load_ALL_Games";
export const Fetch_All_Games = "Fetch_All_Games";
export const Load_Trader_Games = "Load_Trader_Games";
export const Fetch_All_TraderGames = "Fetch_All_TraderGames";
export const Set_GameSession_Id = "Set_GameSession_Id";
export const Join_Game = "Join_Game";
export const Game_Started_ByAdmin = "Game_Started_ByAdmin";
export const Game_Started_Success = "Game_Started_Success";
export const Game_Stopped_ByAdmin = "Game_Stopped_ByAdmin";
export const Game_Deleted_ByAdmin = "Game_Deleted_ByAdmin";
export const Generate_Orders = "Generate_Orders";
export const Close_SnackBar = "Close_SnackBar";
export const Show_SnackBar = "Show_SnackBar";
export const Set_Fetch_Order_Interval = "Set_Fetch_Order_Interval";
//export const Get_Order_Fetch_Interval="Get_Order_Fetch_Interval"
//export const On_Get_Order_Fetch_Interval="On_Get_Order_Fetch_Interval";
export const Load_Portfolio_List = "Load_Portfolio_List";
export const Recieve_Portfolio_List = "Recieve_Portfolio_List";
export const Check_Game_PlayPause = "Check_Game_PlayPause";
export const Set_Game_PlayPause_Status = "Set_Game_PlayPause_Status";
export const Get_GameBased_Dates = "Get_GameBased_Dates";
export const OnFetch_GameBased_Dates="OnFetch_GameBased_Dates";
export const Upload_Game_data="Upload_Game_data";
export const Set_BookOrder_ValidityState="Set_BookOrder_ValidityState";